#include <Arduino.h>
#include <WiZeus_adj_nixie_psu_library.h>

#define SHDN_PIN 12

// Basic way to initialize the module assuming default components
adjNixiePSU myNixiePSU(SHDN_PIN);

// Advanced way to initialize the module.
// Only use this if you know what you are doing and why you need to change anything
// adjNixiePSU myNixiePSU(SHDN_PIN, DEFAULT_R1, DEFAULT_R2, DEFAULT_R_POT_MAX);

void setup()
{

	Serial.begin(115200);
	Serial.println(F("Demo Code for HV Nixie PSU"));

	// Initalize
	myNixiePSU.init();

	// Set Ouput Voltage to 100V
	myNixiePSU.setOutputVoltage(100);

	// Activate the output
	// As long as the output is not enabled, no high voltage will be generated by the module.
	// However residual charge inside the output capacitors can still mean that the output does not return to 0V immediately!
	myNixiePSU.turnOutputOn();

	// Disable the output after 10s
	delay(10000);
	myNixiePSU.turnOutputOff();
}

void loop()
{
}
